.TH sconed 1 "April 2014" "version 1.0.0" "sconeserver"
.SH NAME
sconectl \- sconeserver config/control client
.SH SYNOPSIS
.B sconectl
.RI command
.SH DESCRIPTION
Sends the specified command to the sconeserver daemon, returning the result.

.SH "SEE ALSO"
.B sconed(1),
.br
.B http://www.sconemad.com/sconeserver
for online documentation and latest version.

.SH AUTHOR
Andrew Wedgbury <wedge@sconemad.com>
