#!/usr/bin/perl -w

use IO::Socket;
use IO::Select;

my $HOSTNAME = "localhost";
my $PORT = 80;

my $scd = IO::Socket::INET->new(
  PeerAddr => $HOSTNAME,
  PeerPort => $PORT
);

die "Can't create socket: $!" unless $scd;

if (!$scd->connected()) {
  print "Could not connect\n";
}
#binmode($scd);

my $read_set = IO::Select->new;
$read_set->add($scd);


test_req(
  "GET / HTTP/1.1",
  "User-Agent: scx-test",
  "Host: localhost",
  "If-Modified-Since: Wed, 16 Nov 2005 18:36:41 +0000",
  ""
);

$scd->close();


sub test_req
{
  my $i = 0;
  for ($i=0; $i<1000; ++$i) {
    printf("SEND(%d): %s\n", $i, $_[0]);
    foreach my $line (@_) {
	print $scd "$line\r\n";
    }
  }

  $i = 0;
  while (my $line = <$scd>) {
    chomp $line;
    if ($line =~ /^HTTP/) {
      printf("RECV(%d) %s\n", $i++, $line);
    }
  }
}
