#!/usr/bin/perl -w

use IO::Socket;
use IO::Select;

my $HOSTNAME = "localhost";
my $PORT = 8009;

my $scd = IO::Socket::INET->new(
  PeerAddr => $HOSTNAME,
  PeerPort => $PORT
);

die "Can't create socket: $!" unless $scd;

if (!$scd->connected()) {
  print "Could not connect\n";
}
binmode($scd);

my $read_set = IO::Select->new;
$read_set->add($scd);

while (1) {

  print $scd "stat.all.input\n";
  my ($ready) = IO::Select->select($read_set,undef,undef,undef);
  foreach my $s(@$ready) {
    my $line = <$s>;
    $line =~ s/SconeServer\> //g;
    chomp $line;
    if ($line =~ /^([0-9]+)$/) {
      print "INPUT: $line       \r";
    }
  }
}

$scd->close();
